import{cypress} from "../support/commands"

const cy1 = new cypress()

describe('MyBaseCamp Testing', () => {

    beforeEach(function(){
        cy.visit('http://localhost:3000/')
    })

    it('Verifing Signup button',function() {
        cy1.clickSignup()
        cy1.enterEmailAddress('CypressLearn91@gmail.com')
        cy1.enterUsername('Cypress_learning')
        cy1.enterPassword()
        cy1.clickSubmit()       
    })
    it('Veryfing Login button',function() {
        cy1.clickSignin()
        cy1.enterEmailAddress('CypressLearn91@gmail.com')
        cy1.enterPassword()
        cy1.clickSubmit()
    })
    it('Checking Dashboard',function() {
        cy1.clickSignin()
        cy1.enterEmailAddress('CypressLearn91@gmail.com')
        cy1.enterPassword()
        cy1.clickSubmit()
        cy1.clickdashboard()
        cy1.dashboardverification()        
    })
    it('Checking Profile',function() {
        cy1.clickSignin()
        cy1.enterEmailAddress('CypressLearn91@gmail.com')
        cy1.enterPassword()
        cy1.clickSubmit()
        cy1.clickprofile()
        cy1.profileverification()
    })    
    it('Creating a Project',function(){
        cy1.clickSignin()
        cy1.enterEmailAddress('CypressLearn91@gmail.com')
        cy1.enterPassword()
        cy1.clickSubmit()
        cy1.clickcreateproject()
        cy1.enterprojecttitle('Cypress Class')
        cy1.enterdescription('Learning Cypress step by step')
        cy1.clickSubmit()
        cy1.clickdelete()
    })
    it('Updating description of Project',function(){
        cy1.clickSignin()
        cy1.enterEmailAddress('CypressLearn91@gmail.com')
        cy1.enterPassword()
        cy1.clickSubmit()
        cy1.clickcreateproject()
        cy1.enterprojecttitle('Cypress Class')
        cy1.enterdescription('Learning Cypress step by step')
        cy1.clickSubmit()
        cy1.editicon()
        cy1.editdescription('Learning cypress')
        cy1.clickSubmit()
        cy1.clickdelete()
    })
    it('Deleting a Project',function(){
        cy1.clickSignin()
        cy1.enterEmailAddress('CypressLearn91@gmail.com')
        cy1.enterPassword()
        cy1.clickSubmit()
        cy1.clickcreateproject()
        cy1.enterprojecttitle('Cypress Class')
        cy1.enterdescription('Learning Cypress step by step')
        cy1.clickSubmit()
        cy1.clickdelete()
    })
    it(' Verfing Logout Button',function() {
        cy1.clickSignin()
        cy1.enterEmailAddress('CypressLearn91@gmail.com')
        cy1.enterPassword()
        cy1.clickSubmit()
        cy1.clicklogout()
        cy.get(class{'alert alert-danger'}).contains('You have logged out successfuly! Please login again')
    })
    it('Invalid email id verification', function(){
        cy1.clickSignin()
        cy1.enterEmailAddress('invalidemail@gmail.com')
        cy1.enterPassword()
        cy1.clickSubmit()
        cy1.invalidemailverification()
    })  
    it('Invalid password verification', function(){
        cy1.clickSignin()
        cy1.enterEmailAddress('CypressLearn91@gmail.com')
        cy1.enterinvalidPassword('CyPres123sLeARN12')
        cy1.clickSubmit()
        cy1.invalidpasswordverification()
    })  
    
})
